### ISSUE TITLE
MountainSort4 not importing from spikesorters

### ISSUE THREAD

**Issue by yenhochen** [flatironinstitute/spikeforest_old#74]
I'm following the instructions from spike_sorting_spikeforest_recording.md and I was having trouble getting the tutorial to work. I'm working on a Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-134-generic x86_64) OS using singularity 3.0.1-73.ga50b5b3 and conda 4.7.10. 

I created a new environment (python 3.6.9) for the tutorial and then I get the following error when going through the notebook. 

```
>>> from spikesorters import MountainSort4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MountainSort4'
```
